<Project Sdk="Microsoft.NET.Sdk.Web">

  <ItemGroup>
    <PackageReference Include="Microsoft.IdentityModel.Protocols.OpenIdConnect" />
    <PackageReference Include="System.IdentityModel.Tokens.Jwt" />
    <PackageReference Include="LiteDB" />
    <PackageReference Include="Npgsql" />
    <PackageReference Include="StackExchange.Redis" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="OpenTelemetry.Extensions.Hosting" />
    <PackageReference Include="OpenTelemetry.Instrumentation.AspNetCore" />
    <PackageReference Include="OpenTelemetry.Instrumentation.Http" />
    <PackageReference Include="OpenTelemetry.Exporter.OpenTelemetryProtocol" />
    <PackageReference Include="OpenTelemetry.Exporter.Prometheus.AspNetCore" />
    <ProjectReference Include="..\Mockifyr.Crypto\Mockifyr.Crypto.csproj" />
    <ProjectReference Include="..\Mockifyr.Facade.Http\Mockifyr.Facade.Http.csproj" />
    <ProjectReference Include="..\Mockifyr.Facade.Admin\Mockifyr.Facade.Admin.csproj" />
    <ProjectReference Include="..\Mockifyr.Facade.Grpc\Mockifyr.Facade.Grpc.csproj" />
    <ProjectReference Include="..\Mockifyr.Facade.WebSocket\Mockifyr.Facade.WebSocket.csproj" />
    <ProjectReference Include="..\Mockifyr.Facade.Smtp\Mockifyr.Facade.Smtp.csproj" />
    <ProjectReference Include="..\Mockifyr.Providers.Sms\Mockifyr.Providers.Sms.csproj" />
    <ProjectReference Include="..\Mockifyr.Facade.Library\Mockifyr.Facade.Library.csproj" />
    <ProjectReference Include="..\Mockifyr.Application\Mockifyr.Application.csproj" />
    <ProjectReference Include="..\Mockifyr.Matching\Mockifyr.Matching.csproj" />
    <ProjectReference Include="..\Mockifyr.Templating\Mockifyr.Templating.csproj" />
    <ProjectReference Include="..\Mockifyr.Stores.InMemory\Mockifyr.Stores.InMemory.csproj" />
    <ProjectReference Include="..\Mockifyr.Adapters.MappingJson\Mockifyr.Adapters.MappingJson.csproj" />
    <ProjectReference Include="..\Mockifyr.ServeEvents.Webhook\Mockifyr.ServeEvents.Webhook.csproj" />
    <ProjectReference Include="..\Mockifyr.Outbound\Mockifyr.Outbound.csproj" />
  </ItemGroup>

</Project>
